import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv('MONGO_URI')
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME')
MONGO_COLLECTION_NAME_TEARAPART = os.getenv('MONGO_COLLECTION_NAME_TEARAPART')
MONGO_COLLECTION_NAME_UTPAP = os.getenv('MONGO_COLLECTION_NAME_UTPAP')
MONGO_COLLECTION_NAME_PULLNSAVE = os.getenv('MONGO_COLLECTION_NAME_PULLNSAVE')

MONGO_COLLECTION_NAME_JACKS = os.getenv('MONGO_COLLECTION_NAME_JACKS')
MONGO_COLLECTION_NAME_LKQ = os.getenv('MONGO_COLLECTION_NAME_LKQ')
MONGO_COLLECTION_NAME_PICKNPULL = os.getenv('MONGO_COLLECTION_NAME_PICKNPULL')
MONGO_COLLECTION_NAME_PULLAPART = os.getenv('MONGO_COLLECTION_NAME_PULLAPART')
MONGO_COLLECTION_NAME_UPULLANDSAVE = os.getenv('MONGO_COLLECTION_NAME_UPULLANDSAVE')
