import os
from dotenv import load_dotenv

load_dotenv()

MONGO_URI = os.getenv('MONGO_URI')
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME')
MONGO_COLLECTION_NAME_TEARAPART = os.getenv('MONGO_COLLECTION_NAME_TEARAPART')
MONGO_COLLECTION_NAME_UTPAP = os.getenv('MONGO_COLLECTION_NAME_UTPAP')
MONGO_COLLECTION_NAME_PULLNSAVE = os.getenv('MONGO_COLLECTION_NAME_PULLNSAVE')
